version: "3.9"
services: 

  simple-app:
    image: eko969/hello-app
    networks: 
      - default
    ports: 
      - "3000:3000"
    labels: 
      - com.centurylinklabs.watchtower.enable="true"
  
  watchtower:
    image: containrrr/watchtower
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment: 
      REPO_USER: eko969
      REPO_PASS: Zgdlpro059?
    command: --interval 30

networks: 
  default: